### PR TITLE
(MODULES-3951) Add explicit check for stringify_facts

### PR DESCRIPTION
**Pull request by binford2k**
Without this check, you get incomprehensible results. The is_pe fact is
evaluated as true, and so the class bails out. In some cases the
info() function isn't loud enough and so it appears to do nothing.

This just fails hard and makes it obvious why.

### CODE REVIEW

**Comment by glennsarti** [comment]
Would be nice to get a spec test for this.

**Comment by binford2k** [comment]
@glennsarti I'd be happy to, but I couldn't think of a non-trivial test, and I haven't spent time figuring out how to set up a beaker test with config settings. :-/

**Comment by glennsarti** [comment]
A simple spec test should be sufficient.  Mock the facts and expect a fail.

**Comment by branan** [comment]
This was already done (albeit less-cleanly) here: https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/prepare/ssl.pp#L48-L50

This PR should probably also remove that check, since `stringify_facts` will now explicitly be checked

**Comment by glennsarti** [comment]
Is it possible for that code path to be triggered by something other than stringify = true?

**Comment by branan** [comment]
@glennsarti Only if a user also has their own custom fact called `puppet_sslpaths` that isn't a hash, or if pluginsync has somehow failed - both cases that I'm comfortable not worrying too much about.

https://github.com/puppetlabs/puppetlabs-puppet_agent/commit/6fb63a0b6eaba445a69d62fbe9c4fd0870324504 is the actual commit - the entire `case` is just to check if the fact is a hash.

**Comment by glennsarti** [comment]
Excellent...I can revert those.  Thanks

**Comment by glennsarti** [comment]
@branan travis has completed with the changes you requested.  Can you please review once more and approve once you're happy.  Thanks.

**Pull request merged**
