### PR TITLE
(doc) Update documentation for Windows

### PR DESCRIPTION
**Pull request by glennsarti**
The commit updates the README with examples for Windows based properties.  This
commit also cleans up whitespacing for topic titles.

### CODE REVIEW

**Comment by branan** [comment]
Docs themselves look good. What's up with all the whitespace changes?

**Comment by McdonaldSeanp** [comment]
@branan I assume it's for the purpose of readability in the code itself

**Comment by glennsarti** [comment]
Yes and some markdown previewers don't like it.  Also makes it easier to spot errors like a missing `#` which prompted this whole thing.

**Comment by glennsarti** [comment]
@MikaelSmith @highb For review

**Comment by highb** [comment]
👍

**Pull request merged**
