### PR TITLE
(MODULES-2750) Pass in Puppet agent PID as command line parameter to avoid recreatin…

### PR DESCRIPTION
**Pull request by dhs-rec**
…g install_puppet.bat at every agent run.

### CODE REVIEW

**Comment by ferventcoder** [comment]
I like this.

What we'd like to do here is have you create a ticket on https://tickets.puppetlabs.com/browse/PUP and then update this issue and the commit message with that ticket number. See https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md for more details.

Then it appears you will need to fix up the tests that are now broken based on this change.

**Comment by dhs-rec** [comment]
The ticket is: https://tickets.puppetlabs.com/browse/PA-13

Will look into the tests...

**Comment by ferventcoder** [comment]
Please squash those commits down to one so that specs continue to pass for each commit. Also you are removing test cases, but perhaps it would be good to prove that the command is calling the .bat file with a PID.

**Comment by ferventcoder** [comment]
There is some talk on the ticket about where this should go, PA is probably not the place for the puppet_agent module. I'll wait until there is a decision on where that should go. In the meantime, you can go ahead with the changes I requested. Thanks!

**Comment by kylog** [comment]
This is now https://tickets.puppetlabs.com/browse/MODULES-2750

**Comment by ferventcoder** [comment]
@dhs-rec would you mind updating the commits to be `(MODULES-2750)` instead of `(PA-13)`? Thanks!

**Comment by MikaelSmith** [comment]
@jpartlow you see any problems with this? Tempted to merge it in.

**Pull request merged**
