### PR TITLE
Add use_last_environment config setting

### PR DESCRIPTION
**Pull request by Griphon**
the use_last_environment setting was added in 7.14.0 and it is useful in many cases. Here is the discussion about that:
https://tickets.puppetlabs.com/browse/PA-4297

### CODE REVIEW

**Comment by eringet** [comment]
This PR would be very helpful, so that the puppet agent module can manage this one additional configuration parameter.  Thanks!

**Review by joshcooper — COMMENTED** [review]
Thanks for the PR, could you rebase and resolve conflicts?

**Comment by joshcooper** [comment]
@Griphon could you rebase and resolve conflicts?

**Comment by joshcooper** [comment]
This was fixed in commit 69dada947481dd779d72d43a3543a74e6c951198 so closing this PR as a dup

**Pull request closed without merging**
