### PR TITLE
(MODULES-4236) Disable proxy for yum repo as it will not pass through to Puppet Server and will not hand over the certs.

### PR DESCRIPTION
**Pull request by cyberious**
- We have system wide proxy for all repos and this is critical for us so we can use the module

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Sometimes sourcepath points to a public url. We should probably only disable proxy when source points to a puppet master.

**Comment by cyberious** [comment]
So what do you think is a viable check for internet? not using port `8140`? We override the agent source b/c we use an haproxy and in case one gets overloaded.

**Comment by MikaelSmith** [comment]
That's tricky isn't it. Not using port `8140` might be the best we can do. Alternatively make disabling the proxy a param that can be overridden.

**Comment by cyberious** [comment]
Updated to have as a parameter defaulting to false to maintain the current behavior. Only currently affects redhat

**Pull request merged**
