### PR TITLE
Add parameter puppet_agent::proxy

### PR DESCRIPTION
**Pull request by chrekh**
This is to be able to configure yum-repo with proxy, needed for
example for clients in dmz:s that need to use proxy to reach the repo
provided by puppetserver.

### CODE REVIEW

**Comment by chrekh** [comment]
I tried to add a CLA using the link https://cla.puppet.com/ But it fails to "Authenticate on github", redirecting back to:

```
https://cla.puppet.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=b2118f492751cb957b960d06e9df681adb1c27aa46881684
```

**Comment by lucywyman** [comment]
I think at least the CLA issue has been resolved, if this PR is still relevant?

**Comment by chrekh** [comment]
I still need it.

**Comment by GabrielNagy** [comment]
Hi @chrekh, sorry for the long delay. I pulled your commit into https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/567 where I also updated the documentation and tests, so I'll close this PR.

Thanks for your contribution!

**Pull request closed without merging**
