### PR TITLE
(PE-22505) Add ppc64le to the list of valid architecture regexes

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by ekinanp** [comment]
Does anyone know of a way to test these changes locally and see if they are correct?

**Comment by ekinanp** [comment]
It looks like the case when PUPPET_GEM_VERSION=3.8 failed. Looking at the failures, I am not sure how they can possibly relate to the changes made in my PR (e.g. some of them are failures for OSX).

**Comment by cthorn42** [comment]
@ekinanp I don't know of a super easy way, best way I know is to modify the _agent_upgrade_puppet_agent_module helper method in pe_acceptance_tests, and change what control repo  you are using: https://github.com/puppetlabs/pe_acceptance_tests/blob/2017.3.x/lib/puppet_enterprise_acceptance/setup_helpers.rb#L192
The control repo is what pe_acceptance_tests uses to determine what branch of puppet_agent upgrade module we are using.
You'd then need to have your own branch of control repo that points to your own branch of puppet_agent, you'd do that by modifying https://github.com/puppetlabs/pe_acceptance_tests-control/blob/production/Puppetfile#L11 in the control repo.
Once all that is done and everything is looking in place, you'd want a host.cfg file like this:
```
---
HOSTS:
  centos6-64-1:
    pe_dir: http://enterprise.delivery.puppetlabs.net/archives/releases/2016.4.8/
    pe_ver: 2016.4.8
    pe_upgrade_dir: http://enterprise.delivery.puppetlabs.net/2016.4/ci-ready
    pe_upgrade_ver: 2016.4.9-rc0-18-gd2980dc
    hypervisor: abs
    platform: el-6-x86_64
    packaging_platform: el-6-x86_64
    template: centos-6-x86_64
    roles:
    - agent
    - master
    - dashboard
    - database
  ubuntu1604-POWER-1:
    pe_dir: http://enterprise.delivery.puppetlabs.net/archives/releases/2016.4.8/
    pe_ver: 2016.4.8
    pe_upgrade_dir: http://enterprise.delivery.puppetlabs.net/2016.4/ci-ready
    pe_upgrade_ver: 2016.4.9-rc0-18-gd2980dc
    hypervisor: abs
    platform: ubuntu-16.04-ppc64el
    packaging_platform: ubuntu-16.04-ppc64el
    template: ubuntu-16.04-power8
    roles:
    - agent
    - frictionless
CONFIG:
  nfs_server: none
  consoleport: 443
  forge_host: forge-aio01-petest.puppetlabs.com
```
Where you may need to update the pe_upgrade_ver to whatever http://getpe.delivery.puppetlabs.net/ has for 2016.4.x.
Then the command to run this all is:
**bundle exec beaker -h hosts.cfg --tests acceptance/tests --preserve-hosts onfail --helper lib/beaker_helper.rb --pre-suite setup/install.rb,setup/agent_upgrade.rb --log-level verbose**

That should run your local pe_acceptance_tests that will then goto your branch of pe_acceptance_tests-control that will then use this PR. Hopefully. 
@geoffnichols is there a more sane way to approach this ?

**Comment by ekinanp** [comment]
Ran the tests locally using the following host layouts (from the failing job https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/view/pe-integration/view/pe-2017.3.x/job/enterprise_pe-acceptance-tests_integration-system_pe_non-standard-full-agent-upgrade_non-standard_2017.3.x/49/):

1. centos6-64mcd-ubuntu1604-POWERfa
2. centos6-64mcd-redhat7-POWERfa

upgrading from 2017.3.0 to 2017.3.1 and the pre_suite passed. So this PR should be good to go once the Travis CI issues are fixed.

**Comment by cthorn42** [comment]
@MikaelSmith looks like the travis job using puppet 3.8 has been failing for the last few PRs, should we be okay with merging this as is?

**Comment by MikaelSmith** [comment]
yeah :( I think it was a change in rspec-puppet that no longer supports Puppet 3.8.

**Pull request merged**
