### PR TITLE
(maint) Add Travis badge to README

### PR DESCRIPTION
**Pull request by petems**

### CODE REVIEW

**Comment by glennsarti** [comment]
@petems Can you rebase onto master.  pup 3.8.7 issues should be resolved

**Comment by petems** [comment]
@glennsarti Done! 👍

**Comment by petems** [comment]
@glennsarti There's not much visbility that the module was red without the badge, meant I wasn't sure if my changes broke things or not?

**Comment by glennsarti** [comment]
@MikaelSmith I'm happy to merge.  Can't think of a reason to not have it.

**Pull request merged**
