### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by kylog** [comment]
@mhaskel suggested we add a change log prior to release, /cc @MikaelSmith.

**Comment by MikaelSmith** [comment]
The README mentions centos and fedora, we should probably bring these in-sync.

**Comment by kylog** [comment]
Ah I was going off metadata.json, which says rhel 5/6/7.

**Comment by MikaelSmith** [comment]
We should probably get those in-sync. It should work on any rpm-based distro, but haven't tested it everywhere. Looking at puppetlabs-concat, I'd probably make them all say RedHat 5/6/7 and CentOS 5/6/7.

**Comment by kylog** [comment]
Yeah, I'll do that. Push coming.

**Comment by kylog** [comment]
Okey doke, those should be synced up now.

**Pull request merged**
